# Generated by Django 3.2.9 on 2021-11-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(default='name of the product', max_length=100),
        ),
    ]
