# Generated by Django 3.2.9 on 2021-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_orderitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='name of the product', max_length=20),
        ),
    ]
